version: '3.8'

services:
#  a-trade-data-module:
#    image: localhost/a-trade-data-module:v0.2
#    container_name: a-trade-data-module
#    volumes:
#      - ./a-trade-data-module/data:/persisted_data:Z
#    env_file:
#      - ./a-trade-data-module/.env
#    depends_on:
#      - kafka1
#      - schema-registry
#    environment:
#      KAFKA_BROKER: kafka1:9092
#      data_dir: /persisted_data/ # override from env file
#      shared_resources_dir: /a-trade-data-module/a-trade-shared-resources/ # override from env file
#      schema_registry_url: http://schema-registry:8081
#      kafka_broker: kafka1:9092
#    ports:
#      - "6000:8080"
#
  a-trade-microservice-basic-aggregate-publisher:
    image: localhost/a-trade-microservice-base:latest
    container_name: a-trade-microservice-basic-aggregate-publisher
    ports:
      - "6001:8080"
    volumes:
      - ./a-trade-microservice-basic-aggregate-publisher/build/libs:/app/plugins:Z
      - ./a-trade-data-module/data:/app/data:Z
    depends_on:
      - kafka1
      - schema-registry
    networks:
      - common

  kafka1:
    image: confluentinc/cp-kafka:7.4.10
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9093:9093"  # internal port
    environment:
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: 'EmptNWtoR4GGWx-BH6nGLQ'
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - common

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.10
    container_name: schema-registry
    depends_on:
      - kafka1
    ports:
      - "7002:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9092
    networks:
      - common

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "7000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: a-data-trade-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    depends_on:
      - kafka1
      - schema-registry
    networks:
        - common


volumes:
  kafka_data:

networks:
  common:
    driver: bridge